# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AgoraLive' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AgoraLive
  platform :ios, '9.0'
  
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'HandyJSON'
  pod 'Alamofire', '~> 4.7.3'
  pod 'MJRefresh'
  #pod 'AliyunOSSiOS'
  pod 'AGEVideoLayout'
  pod 'FLAnimatedImage'
  pod 'MBProgressHUD'
  pod 'SVProgressHUD'
  pod 'AlamoClient', '~> 1.0.1'
  
  source 'https://github.com/CocoaPods/Specs.git'
end